# Generated by Django 4.1.2 on 2025-07-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_02',
            field=models.TextField(blank=True, null=True, verbose_name='PE_02. Name of the respondent'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_03',
            field=models.TextField(blank=True, null=True, verbose_name='PE_03. Did respondent give consent?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_04',
            field=models.TextField(blank=True, null=True, verbose_name='PE_04. Household'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_05',
            field=models.TextField(blank=True, null=True, verbose_name='PE_05. What is the name of the head of this household?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_06',
            field=models.TextField(blank=True, null=True, verbose_name='PE_06. Name of Pregnant woman'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_07',
            field=models.TextField(blank=True, null=True, verbose_name='PO_05. What is her Date of Birth?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_07A',
            field=models.IntegerField(blank=True, null=True, verbose_name='PE_07. How old was she at her last birthday?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_08',
            field=models.TextField(blank=True, null=True, verbose_name='PE_08. What is her current marital status?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_09',
            field=models.TextField(blank=True, null=True, verbose_name='PE_09. Do you know her date of  last menstrual period?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_09A',
            field=models.TextField(blank=True, null=True, verbose_name='PE_09A. When was her last menstrual period?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_10',
            field=models.TextField(blank=True, null=True, verbose_name='PE_10. Do you know her expected date of delivery?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_10A',
            field=models.TextField(blank=True, null=True, verbose_name='PE_10A. When is  she  expected date of delivery (EDD)?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_11',
            field=models.TextField(blank=True, null=True, verbose_name='PE_11. Does  she have any of the following medical conditions?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_11_other',
            field=models.TextField(blank=True, null=True, verbose_name='PE_11. Specify other medical conditions.'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_12',
            field=models.TextField(blank=True, null=True, verbose_name='PE_12. Has she  had any complications in her previous pregnancies?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_12_other',
            field=models.TextField(blank=True, null=True, verbose_name='PE_12. Specify other medical conditions.'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_13_specify',
            field=models.TextField(blank=True, null=True, verbose_name='PE_13. Specify Complications'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_14_specify',
            field=models.TextField(blank=True, null=True, verbose_name='PE_14. Specify histrory of genetic conditions'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_15',
            field=models.TextField(blank=True, null=True, verbose_name="PE_15. Does she 'use any form of tobacco (smoked or smokeless)?"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_16',
            field=models.TextField(blank=True, null=True, verbose_name='PE_16. Does she consume alcohol?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_17',
            field=models.TextField(blank=True, null=True, verbose_name='PE_17. How frequent  does she consume alcohol?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_18',
            field=models.TextField(blank=True, null=True, verbose_name='PE_18. Do you have an Antenatal card?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_20',
            field=models.TextField(blank=True, null=True, verbose_name='PE_20. Record the Name of the Facility'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_21',
            field=models.TextField(blank=True, null=True, verbose_name='PE_21. Record the First Antenatal Visit'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_22',
            field=models.IntegerField(blank=True, null=True, verbose_name='PE_22. Record number of Antenatal Visits'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_23',
            field=models.TextField(blank=True, null=True, verbose_name='PE_23. Record HIV Status'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_24',
            field=models.TextField(blank=True, null=True, verbose_name='PE_24. Record Treatment status'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_25',
            field=models.TextField(blank=True, null=True, verbose_name='PE_25. Capture GPS Cordinates for the Household'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='antenatal_card_details',
            field=models.TextField(blank=True, null=True, verbose_name='Atenatal Card Details'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='consented',
            field=models.TextField(blank=True, null=True, verbose_name='Pregnancy Notification'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='constituency',
            field=models.TextField(blank=True, null=True, verbose_name='Select Constituency'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='Select district'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='ea',
            field=models.TextField(blank=True, null=True, verbose_name='Select Enumeration Area'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='enumerator',
            field=models.TextField(blank=True, null=True, verbose_name='Select your name'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='province',
            field=models.TextField(blank=True, null=True, verbose_name='Select province'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='supervisor',
            field=models.TextField(blank=True, null=True, verbose_name='Select your Supervisor name'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='ward',
            field=models.TextField(blank=True, null=True, verbose_name='Select Ward'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_02',
            field=models.TextField(blank=True, null=True, verbose_name='PE_02. Name of the respondent'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_03',
            field=models.TextField(blank=True, null=True, verbose_name='PE_03. Did respondent give consent?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_04',
            field=models.TextField(blank=True, null=True, verbose_name='PE_04. Household'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_05',
            field=models.TextField(blank=True, null=True, verbose_name='PE_05. What is the name of the head of this household?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_06',
            field=models.TextField(blank=True, null=True, verbose_name='PE_06. Name of Pregnant woman'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_07',
            field=models.TextField(blank=True, null=True, verbose_name='PO_05. What is her Date of Birth?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_07A',
            field=models.IntegerField(blank=True, null=True, verbose_name='PE_07. How old was she at her last birthday?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_08',
            field=models.TextField(blank=True, null=True, verbose_name='PE_08. What is her current marital status?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_09',
            field=models.TextField(blank=True, null=True, verbose_name='PE_09. Do you know her date of  last menstrual period?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_09A',
            field=models.TextField(blank=True, null=True, verbose_name='PE_09A. When was her last menstrual period?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_10',
            field=models.TextField(blank=True, null=True, verbose_name='PE_10. Do you know her expected date of delivery?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_10A',
            field=models.TextField(blank=True, null=True, verbose_name='PE_10A. When is  she  expected date of delivery (EDD)?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_11',
            field=models.TextField(blank=True, null=True, verbose_name='PE_11. Does  she have any of the following medical conditions?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_11_other',
            field=models.TextField(blank=True, null=True, verbose_name='PE_11. Specify other medical conditions.'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_12',
            field=models.TextField(blank=True, null=True, verbose_name='PE_12. Has she  had any complications in her previous pregnancies?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_12_other',
            field=models.TextField(blank=True, null=True, verbose_name='PE_12. Specify other medical conditions.'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_13_specify',
            field=models.TextField(blank=True, null=True, verbose_name='PE_13. Specify Complications'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_14_specify',
            field=models.TextField(blank=True, null=True, verbose_name='PE_14. Specify histrory of genetic conditions'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_15',
            field=models.TextField(blank=True, null=True, verbose_name="PE_15. Does she 'use any form of tobacco (smoked or smokeless)?"),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_16',
            field=models.TextField(blank=True, null=True, verbose_name='PE_16. Does she consume alcohol?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_17',
            field=models.TextField(blank=True, null=True, verbose_name='PE_17. How frequent  does she consume alcohol?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_18',
            field=models.TextField(blank=True, null=True, verbose_name='PE_18. Do you have an Antenatal card?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_20',
            field=models.TextField(blank=True, null=True, verbose_name='PE_20. Record the Name of the Facility'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_21',
            field=models.TextField(blank=True, null=True, verbose_name='PE_21. Record the First Antenatal Visit'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_22',
            field=models.IntegerField(blank=True, null=True, verbose_name='PE_22. Record number of Antenatal Visits'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_23',
            field=models.TextField(blank=True, null=True, verbose_name='PE_23. Record HIV Status'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_24',
            field=models.TextField(blank=True, null=True, verbose_name='PE_24. Record Treatment status'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_25',
            field=models.TextField(blank=True, null=True, verbose_name='PE_25. Capture GPS Cordinates for the Household'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='antenatal_card_details',
            field=models.TextField(blank=True, null=True, verbose_name='Atenatal Card Details'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='consented',
            field=models.TextField(blank=True, null=True, verbose_name='Pregnancy Notification'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='constituency',
            field=models.TextField(blank=True, null=True, verbose_name='Select Constituency'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='Select district'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='ea',
            field=models.TextField(blank=True, null=True, verbose_name='Select Enumeration Area'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='enumerator',
            field=models.TextField(blank=True, null=True, verbose_name='Select your name'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='province',
            field=models.TextField(blank=True, null=True, verbose_name='Select province'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='supervisor',
            field=models.TextField(blank=True, null=True, verbose_name='Select your Supervisor name'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='ward',
            field=models.TextField(blank=True, null=True, verbose_name='Select Ward'),
        ),
    ]
