# Generated by Django 4.1.2 on 2025-07-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0005_remove_death_age_at_death_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpregnancy',
            name='PE_07',
            field=models.TextField(blank=True, null=True, verbose_name='PE_07. What is her Date of Birth?'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='PE_07',
            field=models.TextField(blank=True, null=True, verbose_name='PE_07. What is her Date of Birth?'),
        ),
    ]
