# Generated by Django 4.1.2 on 2025-07-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0006_alter_historicalpregnancy_pe_07_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=20, unique=True)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('ea', models.CharField(max_length=100, verbose_name='Enumeration Area')),
            ],
        ),
        migrations.CreateModel(
            name='SRSClusterLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.TextField()),
                ('location_type', models.TextField()),
                ('code', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='household_details',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='usual_residents_group',
        ),
        migrations.RemoveField(
            model_name='household',
            name='household_details',
        ),
        migrations.RemoveField(
            model_name='household',
            name='usual_residents_group',
        ),
        migrations.AddField(
            model_name='historicalhousehold',
            name='submission_date',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='household',
            name='submission_date',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_21',
            field=models.TextField(blank=True, verbose_name='HH_21. How many households occupy this housing unit?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_22B',
            field=models.TextField(verbose_name='HH_22B. In the past two weeks, was the water from your main source not available for at least one full day?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_21',
            field=models.TextField(blank=True, verbose_name='HH_21. How many households occupy this housing unit?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_22B',
            field=models.TextField(verbose_name='HH_22B. In the past two weeks, was the water from your main source not available for at least one full day?'),
        ),
        migrations.AddField(
            model_name='historicalhousehold',
            name='cluster',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='va_data_management.cluster'),
        ),
        migrations.AddField(
            model_name='household',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='va_data_management.cluster'),
        ),
    ]
