# Generated by Django 4.1.2 on 2025-07-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0007_cluster_srsclusterlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhousehold',
            name='HH_04',
            field=models.TextField(blank=True, null=True, verbose_name='HH-04. What is the relationship of to the head of the household? '),
        ),
        migrations.AddField(
            model_name='historicalhousehold',
            name='HH_05',
            field=models.TextField(blank=True, null=True, verbose_name='HH-05. Is member male or Female?'),
        ),
        migrations.AddField(
            model_name='historicalhousehold',
            name='HH_06',
            field=models.TextField(blank=True, null=True, verbose_name="HH-06. Indicate member's Membership Status"),
        ),
        migrations.AddField(
            model_name='household',
            name='HH_04',
            field=models.TextField(blank=True, null=True, verbose_name='HH-04. What is the relationship of to the head of the household? '),
        ),
        migrations.AddField(
            model_name='household',
            name='HH_05',
            field=models.TextField(blank=True, null=True, verbose_name='HH-05. Is member male or Female?'),
        ),
        migrations.AddField(
            model_name='household',
            name='HH_06',
            field=models.TextField(blank=True, null=True, verbose_name="HH-06. Indicate member's Membership Status"),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_01',
            field=models.TextField(blank=True, null=True, verbose_name='HH-01. Name of Head of Household '),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_02',
            field=models.TextField(blank=True, null=True, verbose_name='HH-02. Please give me the number or persons who usually live in this household and the visitors who stayed here last night'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_15',
            field=models.TextField(blank=True, null=True, verbose_name='HH-15. How how long do you intend to stay in this area? Or at this householouhsehold?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_16',
            field=models.TextField(blank=True, null=True, verbose_name='HH-16. TYPE OF HOUSING'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_16A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-61A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_17',
            field=models.TextField(blank=True, null=True, verbose_name='HH-17. What is the main type of material used for the roof?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_17A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-17A.Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_18',
            field=models.TextField(blank=True, null=True, verbose_name='HH-18. What are the walls of this housing unit mainly '),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_18A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-18A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_19',
            field=models.TextField(blank=True, null=True, verbose_name='HH-19. What is the floor of this housing unit mainly'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_19A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-19A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_20',
            field=models.TextField(blank=True, null=True, verbose_name='HH-20. Is this housing unit occupied by one or more households?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_21',
            field=models.TextField(blank=True, null=True, verbose_name='HH-21. How many households occupy this housing unit?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_22',
            field=models.TextField(blank=True, verbose_name='HH-22. What is the main source of water for drinking for this household?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_22A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-22A. In the last month, has there been any time when your household did not have sufficient quantities of drinking water when needed?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_22B',
            field=models.TextField(verbose_name='HH-22B. In the past two weeks, was the water from your main source not available for at least one full day?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_22C',
            field=models.TextField(blank=True, null=True, verbose_name='HH-22C. Do you do anything to make the water safer to drink?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_22D',
            field=models.TextField(blank=True, null=True, verbose_name='HH-22D. What do you usually do to make the water safer to drink?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_22E',
            field=models.TextField(blank=True, null=True, verbose_name='HH-22E. How do you store your drinking water? '),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_22F',
            field=models.TextField(blank=True, null=True, verbose_name='HH-22F. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_23',
            field=models.TextField(blank=True, verbose_name='HH-23. What is the main source of water supply for other purposes such as cooking and handwashing? '),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_24',
            field=models.TextField(blank=True, null=True, verbose_name='HH-24. How many rooms does this housing unit have excluding passage ways, verandas, lobbies, bathrooms and toilet rooms?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_25',
            field=models.TextField(blank=True, null=True, verbose_name='HH-25. How many living rooms and bedrooms does this housing unit have?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_26',
            field=models.TextField(blank=True, null=True, verbose_name='HH-26. How many rooms are used for sleeping in this housing unit?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_27',
            field=models.TextField(blank=True, verbose_name='HH-27. How many persons usually sleep in the housing unit, including those that are not part of the household?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_28',
            field=models.TextField(blank=True, null=True, verbose_name='HH-28. Does this housing unit have a bathoom?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_29',
            field=models.TextField(blank=True, null=True, verbose_name='HH-29. What is the main type of toilet used by members of this household?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_29A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-29A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_30',
            field=models.TextField(blank=True, null=True, verbose_name='HH-30. Is this toilet inside or outside the housing unit? '),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_31',
            field=models.TextField(blank=True, null=True, verbose_name='HH-31. Is this toilet exclusively used by members of this household?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_31A',
            field=models.TextField(blank=True, null=True, verbose_name='31_31A. Including your own household, how many households use this toilet facility?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_32',
            field=models.TextField(blank=True, null=True, verbose_name='HH-32. Does this housing unit have a kitchen?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_33',
            field=models.TextField(blank=True, null=True, verbose_name='HH-33. What is the main source of energy for lighting for this household?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_33A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-33A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_34',
            field=models.TextField(blank=True, null=True, verbose_name='HH-34. What is the main source of energy for cooking for this household?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_34A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-34A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_35',
            field=models.TextField(blank=True, null=True, verbose_name='HH-35. What is the main source of energy for heating for this household?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_35A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-35A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Access_to_internet_at_Home',
            field=models.TextField(blank=True, null=True, verbose_name='Access to internet at Home'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Access_to_internet_away_from_home',
            field=models.TextField(blank=True, null=True, verbose_name='Access to internet away from home'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Agricultural_Land',
            field=models.TextField(blank=True, null=True, verbose_name='Agricultural Land'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Bed',
            field=models.TextField(blank=True, null=True, verbose_name='Bed'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Bicycle',
            field=models.TextField(blank=True, null=True, verbose_name='Bicycle'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Blanket',
            field=models.TextField(blank=True, null=True, verbose_name='Blanket'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Decorder',
            field=models.TextField(blank=True, null=True, verbose_name='Decorder'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Desktop_Laptop_Computer',
            field=models.TextField(blank=True, null=True, verbose_name='Desktop/Laptop Computer'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Fishing_net',
            field=models.TextField(blank=True, null=True, verbose_name='Fishing net'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Fridge',
            field=models.TextField(blank=True, null=True, verbose_name='Fridge'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Generator',
            field=models.TextField(blank=True, null=True, verbose_name='Generator'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Grain_Grinder',
            field=models.TextField(blank=True, null=True, verbose_name='Grain Grinder'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Hammer_Mill',
            field=models.TextField(blank=True, null=True, verbose_name='Hammer Mill'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Hoe',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Landline',
            field=models.TextField(blank=True, null=True, verbose_name='Landline'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Motor_Vehicle',
            field=models.TextField(blank=True, null=True, verbose_name='Motor Vehicle'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Motorcycle',
            field=models.TextField(blank=True, null=True, verbose_name='Motorcycle'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Motorised_Boat',
            field=models.TextField(blank=True, null=True, verbose_name='Motorised Boat'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Non_motorised_Boat',
            field=models.TextField(blank=True, null=True, verbose_name='Non_motorised Boat'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Non_smart_Television',
            field=models.TextField(blank=True, null=True, verbose_name='Non_smart Television'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Plough',
            field=models.TextField(blank=True, null=True, verbose_name='Plough'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Radio',
            field=models.TextField(blank=True, null=True, verbose_name='Radio'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Scotch_Cart',
            field=models.TextField(blank=True, null=True, verbose_name='Scotch Cart'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Smart_Television',
            field=models.TextField(blank=True, null=True, verbose_name='Smart Television'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Sofa',
            field=models.TextField(blank=True, null=True, verbose_name='Sofa'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Stove',
            field=models.TextField(blank=True, null=True, verbose_name='Stove'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Table',
            field=models.TextField(blank=True, null=True, verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Tractor',
            field=models.TextField(blank=True, null=True, verbose_name='Tractor'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_Wheelbarrow',
            field=models.TextField(blank=True, null=True, verbose_name='Wheelbarrow'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_36_group',
            field=models.TextField(blank=True, null=True, verbose_name='HH-36. Does your household have/own any of the following?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_37',
            field=models.TextField(blank=True, null=True, verbose_name='HH-37. Does this household own any livestock, herds, other farm animals, or poultry?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_37A_beef_cattle',
            field=models.TextField(blank=True, null=True, verbose_name='Beef Cattle'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_37A_chicken',
            field=models.TextField(blank=True, null=True, verbose_name='Chicken'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_37A_diary_cattle',
            field=models.TextField(blank=True, null=True, verbose_name='Dairy Cattle'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_37A_goats',
            field=models.TextField(blank=True, null=True, verbose_name='Goats'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_37A_horses_donkeys_mule',
            field=models.TextField(blank=True, null=True, verbose_name='Hourses/Donkeys/Mule'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_37A_pigs',
            field=models.TextField(blank=True, null=True, verbose_name='Pigs'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_37A_rabbits_other_poultry',
            field=models.TextField(blank=True, null=True, verbose_name='Rabbits/Other poultry'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_37A_sheeps',
            field=models.TextField(blank=True, null=True, verbose_name='Sheep'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_37A_traditional_cattle',
            field=models.TextField(blank=True, null=True, verbose_name='Traditional Cattle'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_38',
            field=models.TextField(blank=True, null=True, verbose_name='HH-38. How is the household refuse (garbage) disposed?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_38A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-38A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_39',
            field=models.TextField(blank=True, null=True, verbose_name='HH-39. Is this housing unit owned by any member of this household?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_40',
            field=models.TextField(blank=True, null=True, verbose_name='HH-40. How was this housing unit acquired?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_41',
            field=models.TextField(blank=True, null=True, verbose_name='HH-41. Is this housing unit provided free by the employer,friend or relative of any menber of this household? '),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_42',
            field=models.TextField(blank=True, null=True, verbose_name='HH-42. Is this housing unit rented from the employer of any member of this household?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_43',
            field=models.TextField(blank=True, null=True, verbose_name='HH-43. Who is the employer that provides the housing unit'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_44',
            field=models.TextField(blank=True, null=True, verbose_name='HH-44. From whom is this housing unit rented? '),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='What is the residential address/ village?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='cluster',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='va_data_management.srsclusterlocation'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='code_input',
            field=models.TextField(blank=True, null=True, verbose_name='Survey building number (SBN)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='consent',
            field=models.TextField(blank=True, null=True, verbose_name='Did respondent give consent?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='constituency',
            field=models.TextField(blank=True, null=True, verbose_name='Constituency'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Enter building description'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='deviceid',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='ea',
            field=models.TextField(blank=True, null=True, verbose_name='EA'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='end',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='enumerator',
            field=models.TextField(blank=True, null=True, verbose_name='Enumerator'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='hh_gps',
            field=models.TextField(blank=True, null=True, verbose_name='GPS Cordinates for the Household'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='hhn',
            field=models.TextField(blank=True, null=True, verbose_name='Household  Number (HHN)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='household',
            field=models.TextField(blank=True, null=True, verbose_name='Is there a household?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='household_descriptors',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='household_type',
            field=models.TextField(blank=True, null=True, verbose_name='Type of household'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='hun',
            field=models.TextField(blank=True, null=True, verbose_name='Housing Unit Number (HUN)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='locality_name',
            field=models.TextField(blank=True, null=True, verbose_name='What is the village or locality name?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='name_of_chief',
            field=models.TextField(blank=True, null=True, verbose_name='What is the name of the chief/chieftainess?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='next_visit_date',
            field=models.TextField(blank=True, null=True, verbose_name='Next Visit Date'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='province',
            field=models.TextField(blank=True, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='respondent',
            field=models.TextField(blank=True, null=True, verbose_name="Respondent's Name"),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='result_list',
            field=models.TextField(blank=True, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='result_other',
            field=models.TextField(blank=True, null=True, verbose_name='Other result (Specify)'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='rural_urban',
            field=models.TextField(blank=True, null=True, verbose_name='Rural/urban'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='start',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='submission_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='submit_time',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='supervisor',
            field=models.TextField(blank=True, null=True, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='today',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='visits',
            field=models.TextField(blank=True, null=True, verbose_name='INTERVIEWER VISITS'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='ward',
            field=models.TextField(blank=True, null=True, verbose_name='Ward'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_01',
            field=models.TextField(blank=True, null=True, verbose_name='HH-01. Name of Head of Household '),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_02',
            field=models.TextField(blank=True, null=True, verbose_name='HH-02. Please give me the number or persons who usually live in this household and the visitors who stayed here last night'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_15',
            field=models.TextField(blank=True, null=True, verbose_name='HH-15. How how long do you intend to stay in this area? Or at this householouhsehold?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_16',
            field=models.TextField(blank=True, null=True, verbose_name='HH-16. TYPE OF HOUSING'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_16A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-61A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_17',
            field=models.TextField(blank=True, null=True, verbose_name='HH-17. What is the main type of material used for the roof?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_17A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-17A.Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_18',
            field=models.TextField(blank=True, null=True, verbose_name='HH-18. What are the walls of this housing unit mainly '),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_18A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-18A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_19',
            field=models.TextField(blank=True, null=True, verbose_name='HH-19. What is the floor of this housing unit mainly'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_19A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-19A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_20',
            field=models.TextField(blank=True, null=True, verbose_name='HH-20. Is this housing unit occupied by one or more households?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_21',
            field=models.TextField(blank=True, null=True, verbose_name='HH-21. How many households occupy this housing unit?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_22',
            field=models.TextField(blank=True, verbose_name='HH-22. What is the main source of water for drinking for this household?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_22A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-22A. In the last month, has there been any time when your household did not have sufficient quantities of drinking water when needed?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_22B',
            field=models.TextField(verbose_name='HH-22B. In the past two weeks, was the water from your main source not available for at least one full day?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_22C',
            field=models.TextField(blank=True, null=True, verbose_name='HH-22C. Do you do anything to make the water safer to drink?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_22D',
            field=models.TextField(blank=True, null=True, verbose_name='HH-22D. What do you usually do to make the water safer to drink?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_22E',
            field=models.TextField(blank=True, null=True, verbose_name='HH-22E. How do you store your drinking water? '),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_22F',
            field=models.TextField(blank=True, null=True, verbose_name='HH-22F. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_23',
            field=models.TextField(blank=True, verbose_name='HH-23. What is the main source of water supply for other purposes such as cooking and handwashing? '),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_24',
            field=models.TextField(blank=True, null=True, verbose_name='HH-24. How many rooms does this housing unit have excluding passage ways, verandas, lobbies, bathrooms and toilet rooms?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_25',
            field=models.TextField(blank=True, null=True, verbose_name='HH-25. How many living rooms and bedrooms does this housing unit have?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_26',
            field=models.TextField(blank=True, null=True, verbose_name='HH-26. How many rooms are used for sleeping in this housing unit?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_27',
            field=models.TextField(blank=True, verbose_name='HH-27. How many persons usually sleep in the housing unit, including those that are not part of the household?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_28',
            field=models.TextField(blank=True, null=True, verbose_name='HH-28. Does this housing unit have a bathoom?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_29',
            field=models.TextField(blank=True, null=True, verbose_name='HH-29. What is the main type of toilet used by members of this household?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_29A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-29A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_30',
            field=models.TextField(blank=True, null=True, verbose_name='HH-30. Is this toilet inside or outside the housing unit? '),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_31',
            field=models.TextField(blank=True, null=True, verbose_name='HH-31. Is this toilet exclusively used by members of this household?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_31A',
            field=models.TextField(blank=True, null=True, verbose_name='31_31A. Including your own household, how many households use this toilet facility?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_32',
            field=models.TextField(blank=True, null=True, verbose_name='HH-32. Does this housing unit have a kitchen?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_33',
            field=models.TextField(blank=True, null=True, verbose_name='HH-33. What is the main source of energy for lighting for this household?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_33A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-33A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_34',
            field=models.TextField(blank=True, null=True, verbose_name='HH-34. What is the main source of energy for cooking for this household?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_34A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-34A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_35',
            field=models.TextField(blank=True, null=True, verbose_name='HH-35. What is the main source of energy for heating for this household?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_35A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-35A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Access_to_internet_at_Home',
            field=models.TextField(blank=True, null=True, verbose_name='Access to internet at Home'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Access_to_internet_away_from_home',
            field=models.TextField(blank=True, null=True, verbose_name='Access to internet away from home'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Agricultural_Land',
            field=models.TextField(blank=True, null=True, verbose_name='Agricultural Land'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Bed',
            field=models.TextField(blank=True, null=True, verbose_name='Bed'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Bicycle',
            field=models.TextField(blank=True, null=True, verbose_name='Bicycle'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Blanket',
            field=models.TextField(blank=True, null=True, verbose_name='Blanket'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Decorder',
            field=models.TextField(blank=True, null=True, verbose_name='Decorder'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Desktop_Laptop_Computer',
            field=models.TextField(blank=True, null=True, verbose_name='Desktop/Laptop Computer'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Fishing_net',
            field=models.TextField(blank=True, null=True, verbose_name='Fishing net'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Fridge',
            field=models.TextField(blank=True, null=True, verbose_name='Fridge'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Generator',
            field=models.TextField(blank=True, null=True, verbose_name='Generator'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Grain_Grinder',
            field=models.TextField(blank=True, null=True, verbose_name='Grain Grinder'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Hammer_Mill',
            field=models.TextField(blank=True, null=True, verbose_name='Hammer Mill'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Hoe',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Landline',
            field=models.TextField(blank=True, null=True, verbose_name='Landline'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Motor_Vehicle',
            field=models.TextField(blank=True, null=True, verbose_name='Motor Vehicle'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Motorcycle',
            field=models.TextField(blank=True, null=True, verbose_name='Motorcycle'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Motorised_Boat',
            field=models.TextField(blank=True, null=True, verbose_name='Motorised Boat'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Non_motorised_Boat',
            field=models.TextField(blank=True, null=True, verbose_name='Non_motorised Boat'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Non_smart_Television',
            field=models.TextField(blank=True, null=True, verbose_name='Non_smart Television'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Plough',
            field=models.TextField(blank=True, null=True, verbose_name='Plough'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Radio',
            field=models.TextField(blank=True, null=True, verbose_name='Radio'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Scotch_Cart',
            field=models.TextField(blank=True, null=True, verbose_name='Scotch Cart'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Smart_Television',
            field=models.TextField(blank=True, null=True, verbose_name='Smart Television'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Sofa',
            field=models.TextField(blank=True, null=True, verbose_name='Sofa'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Stove',
            field=models.TextField(blank=True, null=True, verbose_name='Stove'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Table',
            field=models.TextField(blank=True, null=True, verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Tractor',
            field=models.TextField(blank=True, null=True, verbose_name='Tractor'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_Wheelbarrow',
            field=models.TextField(blank=True, null=True, verbose_name='Wheelbarrow'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_36_group',
            field=models.TextField(blank=True, null=True, verbose_name='HH-36. Does your household have/own any of the following?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_37',
            field=models.TextField(blank=True, null=True, verbose_name='HH-37. Does this household own any livestock, herds, other farm animals, or poultry?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_37A_beef_cattle',
            field=models.TextField(blank=True, null=True, verbose_name='Beef Cattle'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_37A_chicken',
            field=models.TextField(blank=True, null=True, verbose_name='Chicken'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_37A_diary_cattle',
            field=models.TextField(blank=True, null=True, verbose_name='Dairy Cattle'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_37A_goats',
            field=models.TextField(blank=True, null=True, verbose_name='Goats'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_37A_horses_donkeys_mule',
            field=models.TextField(blank=True, null=True, verbose_name='Hourses/Donkeys/Mule'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_37A_pigs',
            field=models.TextField(blank=True, null=True, verbose_name='Pigs'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_37A_rabbits_other_poultry',
            field=models.TextField(blank=True, null=True, verbose_name='Rabbits/Other poultry'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_37A_sheeps',
            field=models.TextField(blank=True, null=True, verbose_name='Sheep'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_37A_traditional_cattle',
            field=models.TextField(blank=True, null=True, verbose_name='Traditional Cattle'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_38',
            field=models.TextField(blank=True, null=True, verbose_name='HH-38. How is the household refuse (garbage) disposed?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_38A',
            field=models.TextField(blank=True, null=True, verbose_name='HH-38A. Other (Specify)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_39',
            field=models.TextField(blank=True, null=True, verbose_name='HH-39. Is this housing unit owned by any member of this household?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_40',
            field=models.TextField(blank=True, null=True, verbose_name='HH-40. How was this housing unit acquired?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_41',
            field=models.TextField(blank=True, null=True, verbose_name='HH-41. Is this housing unit provided free by the employer,friend or relative of any menber of this household? '),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_42',
            field=models.TextField(blank=True, null=True, verbose_name='HH-42. Is this housing unit rented from the employer of any member of this household?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_43',
            field=models.TextField(blank=True, null=True, verbose_name='HH-43. Who is the employer that provides the housing unit'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_44',
            field=models.TextField(blank=True, null=True, verbose_name='HH-44. From whom is this housing unit rented? '),
        ),
        migrations.AlterField(
            model_name='household',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='What is the residential address/ village?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='va_data_management.srsclusterlocation'),
        ),
        migrations.AlterField(
            model_name='household',
            name='code_input',
            field=models.TextField(blank=True, null=True, verbose_name='Survey building number (SBN)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='consent',
            field=models.TextField(blank=True, null=True, verbose_name='Did respondent give consent?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='constituency',
            field=models.TextField(blank=True, null=True, verbose_name='Constituency'),
        ),
        migrations.AlterField(
            model_name='household',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Enter building description'),
        ),
        migrations.AlterField(
            model_name='household',
            name='deviceid',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='household',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='household',
            name='ea',
            field=models.TextField(blank=True, null=True, verbose_name='EA'),
        ),
        migrations.AlterField(
            model_name='household',
            name='end',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='household',
            name='enumerator',
            field=models.TextField(blank=True, null=True, verbose_name='Enumerator'),
        ),
        migrations.AlterField(
            model_name='household',
            name='hh_gps',
            field=models.TextField(blank=True, null=True, verbose_name='GPS Cordinates for the Household'),
        ),
        migrations.AlterField(
            model_name='household',
            name='hhn',
            field=models.TextField(blank=True, null=True, verbose_name='Household  Number (HHN)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='household',
            field=models.TextField(blank=True, null=True, verbose_name='Is there a household?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='household_descriptors',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='household',
            name='household_type',
            field=models.TextField(blank=True, null=True, verbose_name='Type of household'),
        ),
        migrations.AlterField(
            model_name='household',
            name='hun',
            field=models.TextField(blank=True, null=True, verbose_name='Housing Unit Number (HUN)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='locality_name',
            field=models.TextField(blank=True, null=True, verbose_name='What is the village or locality name?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='name_of_chief',
            field=models.TextField(blank=True, null=True, verbose_name='What is the name of the chief/chieftainess?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='next_visit_date',
            field=models.TextField(blank=True, null=True, verbose_name='Next Visit Date'),
        ),
        migrations.AlterField(
            model_name='household',
            name='province',
            field=models.TextField(blank=True, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='household',
            name='respondent',
            field=models.TextField(blank=True, null=True, verbose_name="Respondent's Name"),
        ),
        migrations.AlterField(
            model_name='household',
            name='result_list',
            field=models.TextField(blank=True, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='household',
            name='result_other',
            field=models.TextField(blank=True, null=True, verbose_name='Other result (Specify)'),
        ),
        migrations.AlterField(
            model_name='household',
            name='rural_urban',
            field=models.TextField(blank=True, null=True, verbose_name='Rural/urban'),
        ),
        migrations.AlterField(
            model_name='household',
            name='start',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='household',
            name='submission_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='submit_time',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='household',
            name='supervisor',
            field=models.TextField(blank=True, null=True, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='household',
            name='today',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='household',
            name='visits',
            field=models.TextField(blank=True, null=True, verbose_name='INTERVIEWER VISITS'),
        ),
        migrations.AlterField(
            model_name='household',
            name='ward',
            field=models.TextField(blank=True, null=True, verbose_name='Ward'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='HH_03',
            field=models.TextField(blank=True, null=True, verbose_name='HH-03. Household Member Details'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='HH_05',
            field=models.TextField(blank=True, null=True, verbose_name='HH-05. Is he/she male or Female?'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='HH_06',
            field=models.TextField(blank=True, null=True, verbose_name='HH-06. Indicte his/her Membership Status'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='HH_07',
            field=models.TextField(blank=True, null=True, verbose_name='HH-07. What is his/her Date of Birth?'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='HH_11',
            field=models.TextField(blank=True, null=True, verbose_name='HH-11. What is his/her Nationality status'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='HH_14',
            field=models.TextField(blank=True, null=True, verbose_name='HH-14. Is he/she currently pregnant?'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='first_name',
            field=models.TextField(blank=True, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='fullname',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='last_name',
            field=models.TextField(blank=True, null=True, verbose_name='Last name'),
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
