# Generated by Django 4.1.2 on 2025-07-30 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0008_historicalhousehold_hh_04_historicalhousehold_hh_05_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhousehold',
            name='key',
            field=models.CharField(db_index=True, default=99, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='key',
            field=models.CharField(db_index=True, default=99, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='household',
            field=models.ForeignKey(db_column='parent_key', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='va_data_management.household', to_field='key'),
        ),
    ]
