# Generated by Django 4.1.2 on 2025-07-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0009_historicalhousehold_key_household_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_04',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_05',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_06',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_04',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_05',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_06',
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_22B',
            field=models.TextField(blank=True, null=True, verbose_name='HH-22B. In the past two weeks, was the water from your main source not available for at least one full day?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_23',
            field=models.TextField(blank=True, null=True, verbose_name='HH-23. What is the main source of water supply for other purposes such as cooking and handwashing? '),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_27',
            field=models.TextField(blank=True, null=True, verbose_name='HH-27. How many persons usually sleep in the housing unit, including those that are not part of the household?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_37A_animals_group',
            field=models.TextField(blank=True, null=True, verbose_name='HH_37A. How many of the following animals does this household own?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_22B',
            field=models.TextField(blank=True, null=True, verbose_name='HH-22B. In the past two weeks, was the water from your main source not available for at least one full day?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_23',
            field=models.TextField(blank=True, null=True, verbose_name='HH-23. What is the main source of water supply for other purposes such as cooking and handwashing? '),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_27',
            field=models.TextField(blank=True, null=True, verbose_name='HH-27. How many persons usually sleep in the housing unit, including those that are not part of the household?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_37A_animals_group',
            field=models.TextField(blank=True, null=True, verbose_name='HH_37A. How many of the following animals does this household own?'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='HH_04',
            field=models.TextField(blank=True, null=True, verbose_name='HH-04. What is the relationship to the head of the household? '),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='HH_05',
            field=models.TextField(blank=True, null=True, verbose_name='HH-05. Is member male or Female?'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='HH_13',
            field=models.TextField(blank=True, verbose_name='HH_13. In the past two weeks, has he/she experienced any of the following Infectious Health Conditions?'),
        ),
    ]
