# Generated by Django 4.1.2 on 2025-08-01 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('va_data_management', '0010_remove_historicalhousehold_hh_04_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpregnancyoutcome',
            name='PO_49A',
        ),
        migrations.RemoveField(
            model_name='historicalpregnancyoutcome',
            name='PO_49B',
        ),
        migrations.RemoveField(
            model_name='historicalpregnancyoutcome',
            name='PO_49C',
        ),
        migrations.RemoveField(
            model_name='historicalpregnancyoutcome',
            name='PO_49D',
        ),
        migrations.RemoveField(
            model_name='historicalpregnancyoutcome',
            name='PO_49E',
        ),
        migrations.RemoveField(
            model_name='historicalpregnancyoutcome',
            name='PO_50',
        ),
        migrations.RemoveField(
            model_name='pregnancyoutcome',
            name='PO_49A',
        ),
        migrations.RemoveField(
            model_name='pregnancyoutcome',
            name='PO_49B',
        ),
        migrations.RemoveField(
            model_name='pregnancyoutcome',
            name='PO_49C',
        ),
        migrations.RemoveField(
            model_name='pregnancyoutcome',
            name='PO_49D',
        ),
        migrations.RemoveField(
            model_name='pregnancyoutcome',
            name='PO_49E',
        ),
        migrations.RemoveField(
            model_name='pregnancyoutcome',
            name='PO_50',
        ),
        migrations.AddField(
            model_name='historicalpregnancyoutcome',
            name='cluster',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='va_data_management.srsclusterlocation'),
        ),
        migrations.AddField(
            model_name='historicalpregnancyoutcome',
            name='key',
            field=models.CharField(db_index=True, default=99, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregnancyoutcome',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='va_data_management.srsclusterlocation'),
        ),
        migrations.AddField(
            model_name='pregnancyoutcome',
            name='key',
            field=models.CharField(db_index=True, default=99, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PregnancyOutcomeBaby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_49A', models.TextField(blank=True, null=True, verbose_name='PO_49A. Identification of baby')),
                ('PO_49B', models.TextField(blank=True, null=True, verbose_name='PO_49B. Full name')),
                ('PO_49C', models.TextField(blank=True, null=True, verbose_name='PO_49C. Sex of the child')),
                ('PO_49D', models.TextField(blank=True, null=True, verbose_name='PO_49D. Birth weight (Kilograms)')),
                ('PO_49E', models.TextField(blank=True, verbose_name='PO_49E. Was this Birth Registered with the Department of National Registration, Passports and Citizenship (DNRPC)?')),
                ('PO_50', models.TextField(blank=True, verbose_name='PO_50. Do you know the procedure for death Registration and/or Certification as required by DNRPC ?')),
                ('pregnancy_outcome', models.ForeignKey(db_column='parent_key', on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='va_data_management.pregnancyoutcome', to_field='key')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPregnancyOutcomeBaby',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('PO_49A', models.TextField(blank=True, null=True, verbose_name='PO_49A. Identification of baby')),
                ('PO_49B', models.TextField(blank=True, null=True, verbose_name='PO_49B. Full name')),
                ('PO_49C', models.TextField(blank=True, null=True, verbose_name='PO_49C. Sex of the child')),
                ('PO_49D', models.TextField(blank=True, null=True, verbose_name='PO_49D. Birth weight (Kilograms)')),
                ('PO_49E', models.TextField(blank=True, verbose_name='PO_49E. Was this Birth Registered with the Department of National Registration, Passports and Citizenship (DNRPC)?')),
                ('PO_50', models.TextField(blank=True, verbose_name='PO_50. Do you know the procedure for death Registration and/or Certification as required by DNRPC ?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pregnancy_outcome', models.ForeignKey(blank=True, db_column='parent_key', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='va_data_management.pregnancyoutcome', to_field='key')),
            ],
            options={
                'verbose_name': 'historical pregnancy outcome baby',
                'verbose_name_plural': 'historical pregnancy outcome babys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
