# Generated by Django 4.1.2 on 2025-08-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0011_remove_historicalpregnancyoutcome_po_49a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpregnancy',
            name='key',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='key',
            field=models.TextField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
