# Generated by Django 4.1.2 on 2025-08-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0011_remove_historicalpregnancyoutcome_po_49a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='eventid',
            field=models.TextField(blank=True, null=True, verbose_name='Event ID'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='eventid',
            field=models.TextField(blank=True, null=True, verbose_name='Event ID'),
        ),
    ]
