# Generated by Django 4.1.2 on 2025-08-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0012_historicalpregnancy_key_pregnancy_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='key',
            field=models.TextField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='key',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
