# Generated by Django 4.1.2 on 2025-09-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0012_death_eventid_historicaldeath_eventid'),
        ('va_data_management', '0014_dataqualityissue_householdduplicate_and_more'),
    ]

    operations = [
    ]
