# Generated by Django 4.1.2 on 2025-09-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0015_merge_20250919_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalhousehold',
            old_name='submission_date',
            new_name='submissiondate',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='submission_date',
            new_name='submissiondate',
        ),
        migrations.AddField(
            model_name='death',
            name='submissiondate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='submissiondate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpregnancy',
            name='submissiondate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpregnancyoutcome',
            name='submissiondate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='submissiondate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregnancyoutcome',
            name='submissiondate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
