# Generated by Django 4.1.2 on 2026-01-05 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0017_odk_pull_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='odkpulllock',
            new_name='va_data_man_form_id_9972fb_idx',
            old_name='va_data_ma_form_id_5e4e48_idx',
        ),
        migrations.RenameIndex(
            model_name='odkpullstate',
            new_name='va_data_man_form_id_3c351b_idx',
            old_name='va_data_ma_form_id_3c076e_idx',
        ),
    ]
