# Generated by Django 4.1.2 on 2026-02-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0018_rename_va_data_ma_form_id_5e4e48_idx_va_data_man_form_id_9972fb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterLocationCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=100)),
                ('ward_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('cluster_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='death',
            name='death_id',
            field=models.TextField(blank=True, null=True, verbose_name='DEATH ID'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='death_id',
            field=models.TextField(blank=True, null=True, verbose_name='DEATH ID'),
        ),
    ]
