# Generated by Django 4.1.2 on 2026-02-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0019_clusterlocationcodes_death_death_id_and_more'),
        ('va_data_management', '0019_csadailytracker_historicalcsadailytracker'),
    ]

    operations = [
    ]
