# Generated by Django 4.1.2 on 2026-02-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0020_merge_20260218_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalverbalautopsy',
            name='community_va',
            field=models.TextField(blank=True, null=True, verbose_name='Community VA'),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='community_va',
            field=models.TextField(blank=True, null=True, verbose_name='Community VA'),
        ),
    ]
