# Generated by Django 4.1.2 on 2026-02-19 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0022_backfill_community_va_from_hospital_or_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalverbalautopsy',
            name='cluster',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='va_data_management.srsclusterlocation'),
        ),
        migrations.AddField(
            model_name='historicalverbalautopsy',
            name='constituency',
            field=models.TextField(blank=True, null=True, verbose_name='Constituency'),
        ),
        migrations.AddField(
            model_name='historicalverbalautopsy',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='historicalverbalautopsy',
            name='ea',
            field=models.TextField(blank=True, null=True, verbose_name='EA'),
        ),
        migrations.AddField(
            model_name='historicalverbalautopsy',
            name='ward',
            field=models.TextField(blank=True, null=True, verbose_name='Ward'),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verbalautopsies', to='va_data_management.srsclusterlocation'),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='constituency',
            field=models.TextField(blank=True, null=True, verbose_name='Constituency'),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='ea',
            field=models.TextField(blank=True, null=True, verbose_name='EA'),
        ),
        migrations.AddField(
            model_name='verbalautopsy',
            name='ward',
            field=models.TextField(blank=True, null=True, verbose_name='Ward'),
        ),
    ]
