# Generated by Django 4.1.2 on 2025-06-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0024_household_pregnancy_pregnancyoutcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='age_check',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='age_warning',
        ),
        migrations.RemoveField(
            model_name='household',
            name='age_check',
        ),
        migrations.RemoveField(
            model_name='household',
            name='age_warning',
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_04',
            field=models.TextField(blank=True, verbose_name='HH_04. What is the relationship of him/her to the head of the household? '),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_05',
            field=models.TextField(blank=True, verbose_name='HH_05. Is he/she male or Female?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_06',
            field=models.TextField(blank=True, verbose_name='HH_06. Indicte his/her Membership Status'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_07',
            field=models.TextField(blank=True, verbose_name='HH_07. What is his/her Date of Birth?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_08',
            field=models.TextField(blank=True, verbose_name='HH_08. How old was he/she at the last birthday?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_09',
            field=models.TextField(blank=True, verbose_name='HH_09. What is his/her current marital status?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_10',
            field=models.TextField(blank=True, verbose_name='HH_10. How old was he/she when he/she first got married/started cohabiting/living together?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_11',
            field=models.TextField(blank=True, verbose_name='HH_11. What is his/her Nationality status'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_12',
            field=models.TextField(blank=True, verbose_name='HH_12. Does he/she have any of the following medical conditions?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_13',
            field=models.TextField(blank=True, verbose_name='HH_13. In the past two weeks, has he/she experienced any of the following Infectious Health Conditions?                    '),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_14',
            field=models.TextField(blank=True, verbose_name='HH_14. Is he/she currently pregnant?'),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='HH_16',
            field=models.TextField(blank=True, verbose_name='HH_16. TYPE OF HOUSING'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_04',
            field=models.TextField(blank=True, verbose_name='HH_04. What is the relationship of him/her to the head of the household? '),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_05',
            field=models.TextField(blank=True, verbose_name='HH_05. Is he/she male or Female?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_06',
            field=models.TextField(blank=True, verbose_name='HH_06. Indicte his/her Membership Status'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_07',
            field=models.TextField(blank=True, verbose_name='HH_07. What is his/her Date of Birth?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_08',
            field=models.TextField(blank=True, verbose_name='HH_08. How old was he/she at the last birthday?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_09',
            field=models.TextField(blank=True, verbose_name='HH_09. What is his/her current marital status?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_10',
            field=models.TextField(blank=True, verbose_name='HH_10. How old was he/she when he/she first got married/started cohabiting/living together?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_11',
            field=models.TextField(blank=True, verbose_name='HH_11. What is his/her Nationality status'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_12',
            field=models.TextField(blank=True, verbose_name='HH_12. Does he/she have any of the following medical conditions?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_13',
            field=models.TextField(blank=True, verbose_name='HH_13. In the past two weeks, has he/she experienced any of the following Infectious Health Conditions?                    '),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_14',
            field=models.TextField(blank=True, verbose_name='HH_14. Is he/she currently pregnant?'),
        ),
        migrations.AlterField(
            model_name='household',
            name='HH_16',
            field=models.TextField(blank=True, verbose_name='HH_16. TYPE OF HOUSING'),
        ),
    ]
