# Generated by Django 4.1.2 on 2025-06-28 14:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0025_remove_historicalhousehold_age_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_03',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_04',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_05',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_06',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_07',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_08',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_09',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_10',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_11',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_12',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_13',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='HH_14',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='historicalpregnancy',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historicalpregnancyoutcome',
            name='id',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_03',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_04',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_05',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_06',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_07',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_08',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_09',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_10',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_11',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_12',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_13',
        ),
        migrations.RemoveField(
            model_name='household',
            name='HH_14',
        ),
        migrations.RemoveField(
            model_name='household',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='household',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='household',
            name='id',
        ),
        migrations.RemoveField(
            model_name='household',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='household',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='pregnancy',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pregnancyoutcome',
            name='id',
        ),
        migrations.AddField(
            model_name='historicalhousehold',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='historicalpregnancy',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='historicalpregnancyoutcome',
            name='pregnancy',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='va_data_management.pregnancy'),
        ),
        migrations.AddField(
            model_name='historicalpregnancyoutcome',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='household',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pregnancyoutcome',
            name='pregnancy',
            field=models.ForeignKey(default='1e86d2d8-ce55-4d35-a75f-ce64fc324e69', on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='va_data_management.pregnancy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregnancyoutcome',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HH_03', models.TextField(blank=True, verbose_name='HH_03. Household Member Details')),
                ('first_name', models.TextField(blank=True, verbose_name='First name')),
                ('last_name', models.TextField(blank=True, verbose_name='Last name')),
                ('fullname', models.TextField(blank=True, verbose_name='nan')),
                ('HH_04', models.TextField(blank=True, verbose_name='HH_04. What is the relationship of him/her to the head of the household? ')),
                ('HH_05', models.TextField(blank=True, verbose_name='HH_05. Is he/she male or Female?')),
                ('HH_06', models.TextField(blank=True, verbose_name='HH_06. Indicte his/her Membership Status')),
                ('HH_07', models.TextField(blank=True, verbose_name='HH_07. What is his/her Date of Birth?')),
                ('HH_08', models.TextField(blank=True, verbose_name='HH_08. How old was he/she at the last birthday?')),
                ('HH_09', models.TextField(blank=True, verbose_name='HH_09. What is his/her current marital status?')),
                ('HH_10', models.TextField(blank=True, verbose_name='HH_10. How old was he/she when he/she first got married/started cohabiting/living together?')),
                ('HH_11', models.TextField(blank=True, verbose_name='HH_11. What is his/her Nationality status')),
                ('HH_12', models.TextField(blank=True, verbose_name='HH_12. Does he/she have any of the following medical conditions?')),
                ('HH_13', models.TextField(blank=True, verbose_name='HH_13. In the past two weeks, has he/she experienced any of the following Infectious Health Conditions?                    ')),
                ('HH_14', models.TextField(blank=True, verbose_name='HH_14. Is he/she currently pregnant?')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='va_data_management.household')),
            ],
        ),
    ]
