# Generated by Django 4.1.2 on 2025-07-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0028_auto_20250708_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldeath',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, default=0, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalhousehold',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, default=0, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpregnancy',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, default=0, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpregnancyoutcome',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, default=0, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='death',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='household',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
