# Generated by Django 4.1.2 on 2025-07-09 02:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("va_data_management", "0029_historicaldeath_id_historicalhousehold_id_and_more"),
        ("va_data_management", "0029_remove_uuid_fields"),
    ]

    operations = []
