# Generated by Django 4.1.2 on 2025-07-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('download_data', 'Can download data'), ('view_pii', 'Can view PII in data'), ('supervise_users', 'Can supervise other users')),
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
    ]
