# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3

repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.11.12
  hooks:
    - id: ruff-check
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.1.0
  hooks:
    - id: black
