# Generated by Django 4.1.2 on 2025-07-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('va_data_management', '0006_alter_historicalpregnancy_pe_07_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=12, null=True, verbose_name='Staff Code')),
                ('staff_type', models.CharField(choices=[('CSA', 'Community Surveillance Assistant'), ('VA', 'Verbal Autopsy Interviewer')], max_length=12, verbose_name='Staff Type')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff Full Name')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_per', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('cms_status', models.IntegerField(choices=[(1, 'Normal'), (2, 'Duplicate')], null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vacms_staff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.TextField(blank=True, null=True, verbose_name='Device ID')),
                ('instanceid', models.TextField(blank=True, null=True, verbose_name='Instance ID')),
                ('today', models.TextField(blank=True, null=True, verbose_name='Date Recorded')),
                ('start', models.TextField(blank=True, null=True, verbose_name='Form Start Time')),
                ('province', models.TextField(blank=True, null=True, verbose_name='[Select province]')),
                ('district', models.TextField(blank=True, null=True, verbose_name='[Select district]')),
                ('constituency', models.TextField(blank=True, null=True, verbose_name='[Select Constituency]')),
                ('ward', models.TextField(blank=True, null=True, verbose_name='[Select Ward]')),
                ('ea', models.TextField(blank=True, null=True, verbose_name='[Select Enumeration Area]')),
                ('supervisor', models.TextField(blank=True, null=True, verbose_name='Select the name of your supervisor')),
                ('enumerator', models.TextField(blank=True, null=True, verbose_name='Select your name')),
                ('event_type_code', models.TextField(blank=True, null=True, verbose_name='[Select type of event]')),
                ('event_type', models.IntegerField(choices=[(0, 'No Event'), (1, 'Pregnancy'), (2, 'Pregnancy Outcome'), (3, 'Death')], null=True)),
                ('event_status', models.IntegerField(choices=[(0, 'New Death'), (1, 'Interview Scheduled'), (2, 'Interview Completed'), (3, 'Interview On Hold')], null=True)),
                ('interview_proposed_date', models.DateField(blank=True, null=True)),
                ('interview_scheduled_date', models.DateField(blank=True, null=True)),
                ('interview_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_contact_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('form_version', models.CharField(blank=True, max_length=255, null=True)),
                ('death', models.ForeignKey(help_text='Foreign key to the Death.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='death', to='va_data_management.death')),
                ('household', models.ForeignKey(help_text='Foreign key to the Household.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='household', to='va_data_management.household')),
                ('interview_staff', models.ForeignKey(help_text='Foreign key to the Staff.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staff', to='vacms.staff')),
                ('pregnancy', models.ForeignKey(help_text='Foreign key to the Pregnancy.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pregnancy', to='va_data_management.pregnancy')),
                ('pregnancy_outcome', models.ForeignKey(help_text='Foreign key to the Pregnancy Outcome.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pregnancy_outcome', to='va_data_management.pregnancyoutcome')),
            ],
            options={
                'db_table': 'cms_events',
                'managed': True,
            },
        ),
    ]
