# Generated by Django 4.1.2 on 2025-07-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0006_alter_historicalpregnancy_pe_07_and_more'),
        ('vacms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data_collection_staff',
            field=models.ForeignKey(help_text='Foreign key to the Staff.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='data_collection_events', to='vacms.staff'),
        ),
        migrations.AlterField(
            model_name='event',
            name='death',
            field=models.ForeignKey(help_text='Foreign key to the Death.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='va_data_management.death'),
        ),
        migrations.AlterField(
            model_name='event',
            name='household',
            field=models.ForeignKey(blank=True, help_text='Foreign key to the Household.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='va_data_management.household'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pregnancy',
            field=models.ForeignKey(help_text='Foreign key to the Pregnancy.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='va_data_management.pregnancy'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pregnancy_outcome',
            field=models.ForeignKey(help_text='Foreign key to the Pregnancy Outcome.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='va_data_management.pregnancyoutcome'),
        ),
        migrations.AlterField(
            model_name='event',
            name='va',
            field=models.ForeignKey(help_text='Foreign key to the verbal autopsy.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='va_data_management.verbalautopsy'),
        ),
        migrations.AlterField(
            model_name='event',
            name='va_interview_staff',
            field=models.ForeignKey(help_text='Foreign key to the Staff.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='va_interview_events', to='vacms.staff'),
        ),
    ]
