# Generated by Django 4.1.2 on 2025-08-20 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacms', '0002_alter_event_data_collection_staff_alter_event_death_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data_collection_staff',
            field=models.ForeignKey(help_text='Foreign key to the User.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='data_collection_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='va_interview_staff',
            field=models.ForeignKey(help_text='Foreign key to the User.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='va_interview_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
