# Generated by Django 4.1.2 on 2025-12-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacms', '0004_event_va_interview_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='va_not_done_reason',
            field=models.CharField(blank=True, choices=[('relocated', 'Household relocated'), ('dod_outside_period', 'Date of death outside target period'), ('non_resident', 'Deceased not resident of EA'), ('unavailable_rescheduled', 'Unavailable / Rescheduled'), ('refused_denied_access', 'Refused / Denied Access'), ('wrong_household_address', 'Wrong Household / Address'), ('household_outside_ea', 'Household Outside EA'), ('ineligible', 'Ineligible'), ('other', 'Other')], max_length=32, null=True, verbose_name='Reason not done'),
        ),
    ]
