# Generated by Django 4.1.2 on 2026-02-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vacms", "0005_alter_event_va_not_done_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminCommandRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("command_id", models.CharField(max_length=128)),
                ("management_command", models.CharField(max_length=128)),
                ("inputs", models.JSONField(blank=True, default=dict)),
                ("filenames", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("ok", models.BooleanField(default=False)),
                ("output_excerpt", models.TextField(blank=True, default="")),
                ("output_full", models.TextField(blank=True, default="")),
                ("output_file_path", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_command_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "permissions": (
                    ("can_run_admin_commands", "Can run admin panel management commands"),
                ),
            },
        ),
    ]

