# Generated by Django 4.1.2 on 2025-07-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCleanup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('download', 'Can download'), ('bulk_download', 'Can bulk download')),
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
    ]
