# Generated by Django 4.1.2 on 2025-08-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mobile 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mobile 2'),
        ),
    ]
