# Generated by Django 4.1.2 on 2025-12-23 20:35

from django.db import migrations, models
import va_explorer.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=va_explorer.users.models.feedback_attachment_upload_path),
        ),
        migrations.AddField(
            model_name='feedback',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='feedback',
            name='report_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature Request')], default='bug', max_length=16),
        ),
    ]
