# Generated by Django 4.1.2 on 2025-12-24 01:48

import django.core.files.storage
from django.db import migrations, models
import va_explorer.users.models


def normalize_feedback_severity(apps, schema_editor):
    Feedback = apps.get_model("users", "Feedback")
    Feedback.objects.filter(severity="critical").update(severity="high")
    Feedback.objects.filter(severity="enhancement").update(severity="low")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_feedback_attachment_feedback_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/data/uploads/', location='/home/mmwansa/dev/srs-vacms-pilot/va_explorer/static/data/uploads'), upload_to=va_explorer.users.models.feedback_attachment_upload_path),
        ),
        migrations.RunPython(normalize_feedback_severity, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='feedback',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=16),
        ),
    ]
