# Generated by Django 4.1.2 on 2026-01-27 08:58

import django.core.files.storage
from django.db import migrations, models
import va_explorer.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_feedback_attachment_alter_feedback_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='worker_id',
            field=models.CharField(blank=True, null=True, max_length=255, unique=True, verbose_name='Worker ID'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/data/uploads/', location='C:\\Users\\OMEN\\Desktop\\Projects\\srs-vacms-pilot\\va_explorer\\static\\data\\uploads'), upload_to=va_explorer.users.models.feedback_attachment_upload_path),
        ),
    ]
