# Generated by Django 4.1.2 on 2026-01-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_worker_id_alter_feedback_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='worker_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Worker ID'),
        ),
    ]
