# Generated by Django 4.1.2 on 2026-02-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_feedback_attachment'),
        ('users', '0009_alter_user_worker_id'),
    ]

    operations = [
    ]
