# Generated by Django 4.1.2 on 2026-02-25 08:45

import django.core.files.storage
from django.db import migrations, models
import va_explorer.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_feedback_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/data/uploads/', location='/home/mmwansa/dev/github/va_explorer/static/data/uploads'), upload_to=va_explorer.users.models.feedback_attachment_upload_path),
        ),
    ]
